server:
  port: 8080  # 애플리케이션 포트 설정
spring:
  application:
    name: java-mart
  datasource: # H2 DB 연결 설정
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true  # 콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
    database-platform: org.hibernate.dialect.H2Dialect  # JPA에서 사용할 데이터베이스 방언(H2 DB에 맞게 설정)
    hibernate:
      # 데이터베이스 초기화 전략
      # none: 사용하지 않음
      # create: 기존 테이블 삭제 후 데이블 생성
      # create-drop: 기존 테이블 삭제 후 테이블 생성, 종료 시점에 테이블 삭제
      # update: 변경된 스키마 적용
      # validate: 엔티티와 테이블 정상 매핑 확인
      ddl-auto: create # 실행되는 쿼리 출력
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # 쿼리에 물음표로 출력되는 바인드 파라미터 출력
